### ISSUE TITLE
[Nuxt-module] [Windows] - Media related CSS is not loading in production build

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [levchak0910/css-media-splitter#5]
### How to reproduce:
- Install css-media-splitter nuxt module
- Build the project
- Run the project in preview

### Expected result: Base and Media related CSS should be injected on the page

Reproduction link: https://github.com/AndrewBogdanovTSS/fun-css

### System Info:
------------------------------
- Operating System: Windows_NT                                                                                                                                 
- Node Version:     v22.15.0                                                                                                                                   
- Nuxt Version:     3.17.3                                                                                                                                     
- CLI Version:      3.25.1                                                                                                                                     
- Nitro Version:    2.11.11                                                                                                                                    
- Package Manager:  pnpm@10.11.0                                                                                                                               
- Builder:          -                                                                                                                                          
- User Config:      modules, devtools, compatibilityDate, eslint                                                                                               
- Runtime Modules:  @unocss/nuxt@66.1.2, @nuxt/eslint@1.4.0, css-media-splitter/nuxt-module@0.2.7                                                              
- Build Modules:    -                                                                                                                                          
------------------------------

**Comment by levchak0910** [comment]
thanks for providing reproduction )
fixed in v0.2.8

**Comment by AndrewBogdanovTSS** [comment]
@levchak0910 sorry for the delayed response but the issue is not fixed, media related CSS is still not injected with v.2.8.0 and Nuxt 3.17.4, you can use same repo to reproduce the issue. Could you reopen? Thanks

**Comment by levchak0910** [comment]
@AndrewBogdanovTSS I checked your repo again, but the problem is not obvious for me now
Could you please describe what is the issue exactly (and how to reproduce)?

(just in case: module is not working in dev mode)

**Comment by AndrewBogdanovTSS** [comment]
@levchak0910 yes, I'm aware that it's not enabled in dev mode. 
Issue is exactly the same as I specify in the original description. Here is the video comparison of behavior in dev and build
Dev: https://go.screenpal.com/watch/cT1fD3n69P0
Build: https://go.screenpal.com/watch/cT1fDrn69PQ

You can reproduce it by cloning the repo locally and running the build command and then preview

**Comment by levchak0910** [comment]
I am repeating all the steps you wrote, but the issue is not reproducible (

![Image](https://github.com/user-attachments/assets/d7d1bf1c-edd9-4510-98ca-879f70851681)

![Image](https://github.com/user-attachments/assets/84e12c3e-a3d3-4f7d-b4e0-6e46189b06bd)

**Comment by AndrewBogdanovTSS** [comment]
@levchak0910 sorry for the delayed response, I got back to this module and after more throughout testing I see that this issue is only relevant for Windows environment, on MacOS or Ubuntu it loads correctly, it also works well from WSL 2 on Windows 11.
Could you reopen it?

**Comment by levchak0910** [comment]
@AndrewBogdanovTSS reopening it
if you have possibility to fix it - PRs are very welcome )
